from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ReferenceWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(746, 610)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/uiIcon.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(25, 25))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.projectComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectComboBox.sizePolicy().hasHeightForWidth())
        self.projectComboBox.setSizePolicy(sizePolicy)
        self.projectComboBox.setMinimumSize(QtCore.QSize(161, 21))
        self.projectComboBox.setObjectName(_fromUtf8("projectComboBox"))
        self.projectComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.projectComboBox, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.assetTypeComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetTypeComboBox.sizePolicy().hasHeightForWidth())
        self.assetTypeComboBox.setSizePolicy(sizePolicy)
        self.assetTypeComboBox.setObjectName(_fromUtf8("assetTypeComboBox"))
        self.assetTypeComboBox.addItem(_fromUtf8(""))
        self.assetTypeComboBox.addItem(_fromUtf8(""))
        self.assetTypeComboBox.addItem(_fromUtf8(""))
        self.assetTypeComboBox.addItem(_fromUtf8(""))
        self.assetTypeComboBox.addItem(_fromUtf8(""))
        self.assetTypeComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.assetTypeComboBox, 0, 0, 1, 1)
        self.assetSubTypeComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetSubTypeComboBox.sizePolicy().hasHeightForWidth())
        self.assetSubTypeComboBox.setSizePolicy(sizePolicy)
        self.assetSubTypeComboBox.setObjectName(_fromUtf8("assetSubTypeComboBox"))
        self.assetSubTypeComboBox.addItem(_fromUtf8(""))
        self.assetSubTypeComboBox.addItem(_fromUtf8(""))
        self.assetSubTypeComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.assetSubTypeComboBox, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.proxyStateComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxyStateComboBox.sizePolicy().hasHeightForWidth())
        self.proxyStateComboBox.setSizePolicy(sizePolicy)
        self.proxyStateComboBox.setFrame(True)
        self.proxyStateComboBox.setObjectName(_fromUtf8("proxyStateComboBox"))
        self.proxyStateComboBox.addItem(_fromUtf8(""))
        self.proxyStateComboBox.addItem(_fromUtf8(""))
        self.proxyStateComboBox.addItem(_fromUtf8(""))
        self.proxyStateComboBox.addItem(_fromUtf8(""))
        self.proxyStateComboBox.addItem(_fromUtf8(""))
        self.proxyStateComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.proxyStateComboBox, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.iconSmallRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.iconSmallRadioButton.setObjectName(_fromUtf8("iconSmallRadioButton"))
        self.iconSizeButtonGroup = QtGui.QButtonGroup(MainWindow)
        self.iconSizeButtonGroup.setObjectName(_fromUtf8("iconSizeButtonGroup"))
        self.iconSizeButtonGroup.addButton(self.iconSmallRadioButton)
        self.gridLayout.addWidget(self.iconSmallRadioButton, 0, 5, 1, 1)
        self.iconMediumRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.iconMediumRadioButton.setObjectName(_fromUtf8("iconMediumRadioButton"))
        self.iconSizeButtonGroup.addButton(self.iconMediumRadioButton)
        self.gridLayout.addWidget(self.iconMediumRadioButton, 0, 6, 1, 1)
        self.iconBigRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.iconBigRadioButton.setObjectName(_fromUtf8("iconBigRadioButton"))
        self.iconSizeButtonGroup.addButton(self.iconBigRadioButton)
        self.gridLayout.addWidget(self.iconBigRadioButton, 0, 7, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 8, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setAutoScrollMargin(5)
        self.listWidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.listWidget.setProperty(_fromUtf8("showDropIndicator"), False)
        self.listWidget.setIconSize(QtCore.QSize(120, 200))
        self.listWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setMovement(QtGui.QListView.Static)
        self.listWidget.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget.setGridSize(QtCore.QSize(120, 120))
        self.listWidget.setViewMode(QtGui.QListView.IconMode)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_2.addWidget(self.listWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp_on_ReferenceLib = QtGui.QAction(MainWindow)
        self.actionHelp_on_ReferenceLib.setObjectName(_fromUtf8("actionHelp_on_ReferenceLib"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp_on_ReferenceLib)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.assetTypeComboBox, self.assetSubTypeComboBox)
        MainWindow.setTabOrder(self.assetSubTypeComboBox, self.proxyStateComboBox)
        MainWindow.setTabOrder(self.proxyStateComboBox, self.listWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ReferenceLib", None, QtGui.QApplication.UnicodeUTF8))
        self.iconSmallRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Small", None, QtGui.QApplication.UnicodeUTF8))
        self.iconMediumRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.iconBigRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Big", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp_on_ReferenceLib.setText(QtGui.QApplication.translate("MainWindow", "Help on ReferenceLib", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
