from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ShotOpenMainWindow(object):
    def setupUi(self, ShotOpenMainWindow):
        ShotOpenMainWindow.setObjectName(_fromUtf8("ShotOpenMainWindow"))
        ShotOpenMainWindow.resize(444, 572)
        self.centralwidget = QtGui.QWidget(ShotOpenMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.filmLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.filmLabel.setFont(font)
        self.filmLabel.setObjectName(_fromUtf8("filmLabel"))
        self.gridLayout.addWidget(self.filmLabel, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(128, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 2)
        self.filmComboBox = QtGui.QComboBox(self.centralwidget)
        self.filmComboBox.setMinimumSize(QtCore.QSize(121, 22))
        self.filmComboBox.setMaximumSize(QtCore.QSize(121, 22))
        self.filmComboBox.setObjectName(_fromUtf8("filmComboBox"))
        self.gridLayout.addWidget(self.filmComboBox, 1, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.episodeComboBox = QtGui.QComboBox(self.centralwidget)
        self.episodeComboBox.setMinimumSize(QtCore.QSize(121, 22))
        self.episodeComboBox.setMaximumSize(QtCore.QSize(121, 22))
        self.episodeComboBox.setObjectName(_fromUtf8("episodeComboBox"))
        self.gridLayout.addWidget(self.episodeComboBox, 2, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.exportLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.exportLabel.setFont(font)
        self.exportLabel.setObjectName(_fromUtf8("exportLabel"))
        self.gridLayout_2.addWidget(self.exportLabel, 0, 0, 1, 2)
        self.exportPushButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.exportPushButton.setFont(font)
        self.exportPushButton.setObjectName(_fromUtf8("exportPushButton"))
        self.gridLayout_2.addWidget(self.exportPushButton, 1, 1, 1, 1)
        self.exportComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportComboBox.sizePolicy().hasHeightForWidth())
        self.exportComboBox.setSizePolicy(sizePolicy)
        self.exportComboBox.setMinimumSize(QtCore.QSize(131, 22))
        self.exportComboBox.setMaximumSize(QtCore.QSize(131, 22))
        self.exportComboBox.setObjectName(_fromUtf8("exportComboBox"))
        self.gridLayout_2.addWidget(self.exportComboBox, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.folderListWidget = QtGui.QListWidget(self.centralwidget)
        self.folderListWidget.setObjectName(_fromUtf8("folderListWidget"))
        self.gridLayout_3.addWidget(self.folderListWidget, 1, 0, 1, 1)
        self.fileListWidget = QtGui.QListWidget(self.centralwidget)
        self.fileListWidget.setObjectName(_fromUtf8("fileListWidget"))
        self.gridLayout_3.addWidget(self.fileListWidget, 1, 1, 1, 1)
        ShotOpenMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ShotOpenMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 444, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ShotOpenMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ShotOpenMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ShotOpenMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ShotOpenMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ShotOpenMainWindow)

    def retranslateUi(self, ShotOpenMainWindow):
        ShotOpenMainWindow.setWindowTitle(QtGui.QApplication.translate("ShotOpenMainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.filmLabel.setText(QtGui.QApplication.translate("ShotOpenMainWindow", "Film", None, QtGui.QApplication.UnicodeUTF8))
        self.exportLabel.setText(QtGui.QApplication.translate("ShotOpenMainWindow", "Export selected file to:", None, QtGui.QApplication.UnicodeUTF8))
        self.exportPushButton.setText(QtGui.QApplication.translate("ShotOpenMainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))

