# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U:\dsCore\maya\dsShotOpen\dsShotOpenUI.ui'
#
# Created: Fri Oct 04 13:52:24 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 681)
        MainWindow.setMinimumSize(QtCore.QSize(452, 681))
        MainWindow.setMaximumSize(QtCore.QSize(452, 681))
        #MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.user_L = QtGui.QLabel(self.centralwidget)
        self.user_L.setMaximumSize(QtCore.QSize(201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.user_L.setFont(font)
        self.user_L.setObjectName("user_L")
        self.verticalLayout_2.addWidget(self.user_L)
        self.user_CB = QtGui.QComboBox(self.centralwidget)
        self.user_CB.setMinimumSize(QtCore.QSize(199, 20))
        self.user_CB.setObjectName("user_CB")
        self.verticalLayout_2.addWidget(self.user_CB)
        self.project_L = QtGui.QLabel(self.centralwidget)
        self.project_L.setMaximumSize(QtCore.QSize(201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.project_L.setFont(font)
        self.project_L.setObjectName("project_L")
        self.verticalLayout_2.addWidget(self.project_L)
        self.projects_CB = QtGui.QComboBox(self.centralwidget)
        self.projects_CB.setMinimumSize(QtCore.QSize(199, 20))
        self.projects_CB.setObjectName("projects_CB")
        self.verticalLayout_2.addWidget(self.projects_CB)
        self.episode_L = QtGui.QLabel(self.centralwidget)
        self.episode_L.setMaximumSize(QtCore.QSize(201, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.episode_L.setFont(font)
        self.episode_L.setObjectName("episode_L")
        self.verticalLayout_2.addWidget(self.episode_L)
        self.episodes_CB = QtGui.QComboBox(self.centralwidget)
        self.episodes_CB.setMinimumSize(QtCore.QSize(199, 20))
        self.episodes_CB.setObjectName("episodes_CB")
        self.verticalLayout_2.addWidget(self.episodes_CB)
        self.seq_L = QtGui.QLabel(self.centralwidget)
        self.seq_L.setMaximumSize(QtCore.QSize(201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.seq_L.setFont(font)
        self.seq_L.setObjectName("seq_L")
        self.verticalLayout_2.addWidget(self.seq_L)
        self.sequence_CB = QtGui.QComboBox(self.centralwidget)
        self.sequence_CB.setMinimumSize(QtCore.QSize(199, 20))
        self.sequence_CB.setObjectName("sequence_CB")
        self.verticalLayout_2.addWidget(self.sequence_CB)
        self.task_L = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.task_L.setFont(font)
        self.task_L.setObjectName("task_L")
        self.verticalLayout_2.addWidget(self.task_L)
        self.task_CB = QtGui.QComboBox(self.centralwidget)
        self.task_CB.setMinimumSize(QtCore.QSize(199, 20))
        self.task_CB.setObjectName("task_CB")
        self.verticalLayout_2.addWidget(self.task_CB)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scene_L = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scene_L.sizePolicy().hasHeightForWidth())
        self.scene_L.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.scene_L.setFont(font)
        self.scene_L.setObjectName("scene_L")
        self.gridLayout_2.addWidget(self.scene_L, 0, 0, 1, 1)
        self.hero_RB = QtGui.QRadioButton(self.centralwidget)
        self.hero_RB.setEnabled(True)
        self.hero_RB.setMinimumSize(QtCore.QSize(55, 17))
        self.hero_RB.setMaximumSize(QtCore.QSize(47, 17))
        self.hero_RB.setChecked(True)
        self.hero_RB.setObjectName("hero_RB")
        self.gridLayout_2.addWidget(self.hero_RB, 0, 1, 1, 1)
        self.version_RB = QtGui.QRadioButton(self.centralwidget)
        self.version_RB.setEnabled(False)
        self.version_RB.setMinimumSize(QtCore.QSize(55, 17))
        self.version_RB.setMaximumSize(QtCore.QSize(47, 17))
        self.version_RB.setChecked(False)
        self.version_RB.setObjectName("version_RB")
        self.gridLayout_2.addWidget(self.version_RB, 0, 2, 1, 1)
        self.scene_LW = QtGui.QListWidget(self.centralwidget)
        self.scene_LW.setMinimumSize(QtCore.QSize(211, 400))
        self.scene_LW.setIconSize(QtCore.QSize(100, 500))
        self.scene_LW.setObjectName("scene_LW")
        self.gridLayout_2.addWidget(self.scene_LW, 1, 0, 1, 4)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 4, 1)
        self.shots_L = QtGui.QLabel(self.centralwidget)
        self.shots_L.setObjectName("shots_L")
        self.gridLayout.addWidget(self.shots_L, 1, 0, 1, 1)
        self.shots_LW = QtGui.QListWidget(self.centralwidget)
        self.shots_LW.setMinimumSize(QtCore.QSize(201, 175))
        self.shots_LW.setMaximumSize(QtCore.QSize(201, 175))
        self.shots_LW.setFrameShape(QtGui.QFrame.NoFrame)
        self.shots_LW.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.shots_LW.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shots_LW.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.shots_LW.setObjectName("shots_LW")
        self.gridLayout.addWidget(self.shots_LW, 2, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.createEmpty_B = QtGui.QPushButton(self.centralwidget)
        self.createEmpty_B.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createEmpty_B.sizePolicy().hasHeightForWidth())
        self.createEmpty_B.setSizePolicy(sizePolicy)
        self.createEmpty_B.setMinimumSize(QtCore.QSize(201, 31))
        self.createEmpty_B.setMaximumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.createEmpty_B.setFont(font)
        self.createEmpty_B.setObjectName("createEmpty_B")
        self.verticalLayout.addWidget(self.createEmpty_B)
        self.versionUp_B = QtGui.QPushButton(self.centralwidget)
        self.versionUp_B.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionUp_B.sizePolicy().hasHeightForWidth())
        self.versionUp_B.setSizePolicy(sizePolicy)
        self.versionUp_B.setMinimumSize(QtCore.QSize(201, 31))
        self.versionUp_B.setMaximumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.versionUp_B.setFont(font)
        self.versionUp_B.setObjectName("versionUp_B")
        self.verticalLayout.addWidget(self.versionUp_B)
        self.saveAs_B = QtGui.QPushButton(self.centralwidget)
        self.saveAs_B.setMinimumSize(QtCore.QSize(201, 31))
        self.saveAs_B.setMaximumSize(QtCore.QSize(201, 31))
        self.saveAs_B.setObjectName("saveAs_B")
        self.verticalLayout.addWidget(self.saveAs_B)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(201, 31))
        self.splitter.setMaximumSize(QtCore.QSize(200, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setObjectName("splitter")
        self.ref_B = QtGui.QPushButton(self.splitter)
        self.ref_B.setMinimumSize(QtCore.QSize(100, 31))
        self.ref_B.setMaximumSize(QtCore.QSize(100, 31))
        self.ref_B.setObjectName("ref_B")
        self.import_B = QtGui.QPushButton(self.splitter)
        self.import_B.setMinimumSize(QtCore.QSize(100, 31))
        self.import_B.setMaximumSize(QtCore.QSize(99, 31))
        self.import_B.setObjectName("import_B")
        self.verticalLayout.addWidget(self.splitter)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setMinimumSize(QtCore.QSize(201, 31))
        self.splitter_2.setMaximumSize(QtCore.QSize(200, 31))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setHandleWidth(1)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.export_B = QtGui.QPushButton(self.splitter_2)
        self.export_B.setMinimumSize(QtCore.QSize(100, 31))
        self.export_B.setMaximumSize(QtCore.QSize(100, 31))
        self.export_B.setObjectName("export_B")
        self.retire_B = QtGui.QPushButton(self.splitter_2)
        self.retire_B.setMinimumSize(QtCore.QSize(100, 31))
        self.retire_B.setMaximumSize(QtCore.QSize(99, 31))
        self.retire_B.setObjectName("retire_B")
        self.verticalLayout.addWidget(self.splitter_2)
        self.notate_B = QtGui.QPushButton(self.centralwidget)
        self.notate_B.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notate_B.sizePolicy().hasHeightForWidth())
        self.notate_B.setSizePolicy(sizePolicy)
        self.notate_B.setMinimumSize(QtCore.QSize(201, 31))
        self.notate_B.setMaximumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.notate_B.setFont(font)
        self.notate_B.setObjectName("notate_B")
        self.verticalLayout.addWidget(self.notate_B)
        self.sg_B = QtGui.QPushButton(self.centralwidget)
        self.sg_B.setMinimumSize(QtCore.QSize(201, 31))
        self.sg_B.setMaximumSize(QtCore.QSize(201, 31))
        self.sg_B.setObjectName("sg_B")
        self.verticalLayout.addWidget(self.sg_B)
        self.explorer_B = QtGui.QPushButton(self.centralwidget)
        self.explorer_B.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.explorer_B.sizePolicy().hasHeightForWidth())
        self.explorer_B.setSizePolicy(sizePolicy)
        self.explorer_B.setMinimumSize(QtCore.QSize(201, 31))
        self.explorer_B.setMaximumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.explorer_B.setFont(font)
        self.explorer_B.setObjectName("explorer_B")
        self.verticalLayout.addWidget(self.explorer_B)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 1)
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 18))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)
        self.actionVfx_wiki_dk = QtGui.QAction(MainWindow)
        self.actionVfx_wiki_dk.setObjectName("actionVfx_wiki_dk")
        self.menuHelp.addAction(self.actionVfx_wiki_dk)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "dsShotOpen", None, QtGui.QApplication.UnicodeUTF8))
        self.user_L.setText(QtGui.QApplication.translate("MainWindow", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.project_L.setText(QtGui.QApplication.translate("MainWindow", "Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.episode_L.setText(QtGui.QApplication.translate("MainWindow", "Episode:", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_L.setText(QtGui.QApplication.translate("MainWindow", "Sequence:", None, QtGui.QApplication.UnicodeUTF8))
        self.task_L.setText(QtGui.QApplication.translate("MainWindow", "Task:", None, QtGui.QApplication.UnicodeUTF8))
        self.scene_L.setText(QtGui.QApplication.translate("MainWindow", "Scene:", None, QtGui.QApplication.UnicodeUTF8))
        self.hero_RB.setText(QtGui.QApplication.translate("MainWindow", "Hero", None, QtGui.QApplication.UnicodeUTF8))
        self.version_RB.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.shots_L.setText(QtGui.QApplication.translate("MainWindow", "Shots In Sequence:", None, QtGui.QApplication.UnicodeUTF8))
        self.createEmpty_B.setText(QtGui.QApplication.translate("MainWindow", "Create Empty Scene ", None, QtGui.QApplication.UnicodeUTF8))
        self.versionUp_B.setText(QtGui.QApplication.translate("MainWindow", "Version Up", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAs_B.setText(QtGui.QApplication.translate("MainWindow", "SaveAS", None, QtGui.QApplication.UnicodeUTF8))
        self.ref_B.setText(QtGui.QApplication.translate("MainWindow", "ref", None, QtGui.QApplication.UnicodeUTF8))
        self.import_B.setText(QtGui.QApplication.translate("MainWindow", "import", None, QtGui.QApplication.UnicodeUTF8))
        self.export_B.setText(QtGui.QApplication.translate("MainWindow", "export Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.retire_B.setText(QtGui.QApplication.translate("MainWindow", "retire", None, QtGui.QApplication.UnicodeUTF8))
        self.notate_B.setText(QtGui.QApplication.translate("MainWindow", "Notate Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.sg_B.setText(QtGui.QApplication.translate("MainWindow", "SHOTGUN", None, QtGui.QApplication.UnicodeUTF8))
        self.explorer_B.setText(QtGui.QApplication.translate("MainWindow", "Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVfx_wiki_dk.setText(QtGui.QApplication.translate("MainWindow", "wiki", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVfx_wiki_dk.setIconText(QtGui.QApplication.translate("MainWindow", "wiki", None, QtGui.QApplication.UnicodeUTF8))

