from PyQt4 import QtCore, QtGui

##Remove Dialog
class Ui_RemoveSetDialog(QtGui.QDialog):
    '''
    '''
    def __init__(self, setType=None, item=None, parent=None):
        super(Ui_RemoveSetDialog, self).__init__(parent)
        self.setWindowTitle("Delete %s Dialog" % setType)

        self.setObjectName("Dialog")
        self.resize(100, 80)
        self.gridLayout = QtGui.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(27, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtGui.QLabel("Delete %s" % item)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 2)

        self.deletePushButton = QtGui.QPushButton("Delete")
        self.gridLayout.addWidget(self.deletePushButton, 2, 0, 1, 2)
        self.cancelPushButton = QtGui.QPushButton("Cancel")
        self.cancelPushButton.clicked.connect(self.close)
        self.gridLayout.addWidget(self.cancelPushButton, 2, 2, 1, 2)

        QtCore.QMetaObject.connectSlotsByName(self)


##Create Dialog
class Ui_Dialog(QtGui.QDialog):
    """
    """
    def __init__(self, setType=None, parent=None):
        super(Ui_Dialog, self).__init__(parent)
        self.setWindowTitle("%s Dialog" % setType)

        self.setObjectName("Dialog")
        self.resize(215, 181)

        self.gridLayout = QtGui.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel("Create %s Set" % setType)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")

        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.comboBox = QtGui.QComboBox(self)
        self.comboBox.setObjectName("comboBox")

        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 2)
        self.checkBox = QtGui.QCheckBox("Add Selected to Set")
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 2)
        self.lineEdit = QtGui.QLineEdit(self)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 0, 1, 2)
        self.okPushButton = QtGui.QPushButton("Create")
        self.gridLayout.addWidget(self.okPushButton, 4, 0, 1, 1)
        self.cancelPushButton = QtGui.QPushButton("Cancel")
        self.cancelPushButton.clicked.connect(self.close)
        self.gridLayout.addWidget(self.cancelPushButton, 4, 1, 1, 1)


##Main Window
class Ui_dsPublishSetsGUI(object):
    '''
    '''
    def setupUi(self, SubAssetWindow):
        SubAssetWindow.setObjectName("SubAssetWindow")
        SubAssetWindow.resize(371, 396)
        self.centralwidget = QtGui.QWidget(SubAssetWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.isolateViewCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.isolateViewCheckBox.setObjectName("isolateViewCheckBox")
        self.gridLayout.addWidget(self.isolateViewCheckBox, 0, 0, 1, 1)
        self.subAssetLabel = QtGui.QLabel(self.centralwidget)
        self.subAssetLabel.setObjectName("subAssetLabel")
        self.gridLayout.addWidget(self.subAssetLabel, 1, 0, 1, 1)
        self.proxyLabel = QtGui.QLabel(self.centralwidget)
        self.proxyLabel.setObjectName("proxyLabel")
        self.gridLayout.addWidget(self.proxyLabel, 1, 1, 1, 1)
        self.subAssetListWidget = QtGui.QListWidget(self.centralwidget)
        self.subAssetListWidget.setObjectName("subAssetListWidget")
        QtGui.QListWidgetItem(self.subAssetListWidget)
        self.gridLayout.addWidget(self.subAssetListWidget, 2, 0, 1, 1)
        self.proxyListWidget = QtGui.QListWidget(self.centralwidget)
        self.proxyListWidget.setObjectName("proxyListWidget")
        QtGui.QListWidgetItem(self.proxyListWidget)
        self.gridLayout.addWidget(self.proxyListWidget, 2, 1, 1, 1)
        self.createSubAssetPushButton = QtGui.QPushButton(self.centralwidget)
        self.createSubAssetPushButton.setObjectName("createSubAssetPushButton")
        self.gridLayout.addWidget(self.createSubAssetPushButton, 3, 0, 1, 1)
        self.createProxyPushButton = QtGui.QPushButton(self.centralwidget)
        self.createProxyPushButton.setObjectName("createProxyPushButton")
        self.gridLayout.addWidget(self.createProxyPushButton, 3, 1, 1, 1)
        self.removeSubAssetPushButton = QtGui.QPushButton(self.centralwidget)
        self.removeSubAssetPushButton.setObjectName("removeSubAssetPushButton")
        self.gridLayout.addWidget(self.removeSubAssetPushButton, 4, 0, 1, 1)
        self.removeProxyPushButton = QtGui.QPushButton(self.centralwidget)
        self.removeProxyPushButton.setObjectName("removeProxyPushButton")
        self.gridLayout.addWidget(self.removeProxyPushButton, 4, 1, 1, 1)
        self.addSelSubAssetPushButton = QtGui.QPushButton(self.centralwidget)
        self.addSelSubAssetPushButton.setObjectName("addSelSubAssetPushButton")
        self.gridLayout.addWidget(self.addSelSubAssetPushButton, 5, 0, 1, 1)
        self.addSelProxyPushButton = QtGui.QPushButton(self.centralwidget)
        self.addSelProxyPushButton.setObjectName("addSelProxyPushButton")
        self.gridLayout.addWidget(self.addSelProxyPushButton, 5, 1, 1, 1)
        self.removeSelSubAssetPushButton = QtGui.QPushButton(self.centralwidget)
        self.removeSelSubAssetPushButton.setMinimumSize(QtCore.QSize(171, 23))
        self.removeSelSubAssetPushButton.setObjectName("removeSelSubAssetPushButton")
        self.gridLayout.addWidget(self.removeSelSubAssetPushButton, 6, 0, 1, 1)
        self.removeSelProxyPushButton = QtGui.QPushButton(self.centralwidget)
        self.removeSelProxyPushButton.setMaximumSize(QtCore.QSize(171, 23))
        self.removeSelProxyPushButton.setObjectName("removeSelProxyPushButton")
        self.gridLayout.addWidget(self.removeSelProxyPushButton, 6, 1, 1, 1)
        SubAssetWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SubAssetWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 21))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        SubAssetWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SubAssetWindow)
        self.statusbar.setObjectName("statusbar")
        SubAssetWindow.setStatusBar(self.statusbar)
        self.actionHelp_on_AssetDialog = QtGui.QAction(SubAssetWindow)
        self.actionHelp_on_AssetDialog.setObjectName("actionHelp_on_subSetDialog")
        self.actionAbout = QtGui.QAction(SubAssetWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtGui.QAction(SubAssetWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionIsolateView = QtGui.QAction(SubAssetWindow)
        self.actionIsolateView.setObjectName("Isolate View")

        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.menuEdit.addAction(self.actionExit)
        self.menuView.addAction(self.actionIsolateView)
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(SubAssetWindow)
        QtCore.QMetaObject.connectSlotsByName(SubAssetWindow)

    def retranslateUi(self, SubAssetWindow):
        SubAssetWindow.setWindowTitle(QtGui.QApplication.translate("SubAssetWindow", "SubAsset and Proxy Creator", None, QtGui.QApplication.UnicodeUTF8))
        self.isolateViewCheckBox.setText(QtGui.QApplication.translate("SubAssetWindow", "Isolate View", None, QtGui.QApplication.UnicodeUTF8))
        self.subAssetLabel.setText(QtGui.QApplication.translate("SubAssetWindow", "SubAsset List:", None, QtGui.QApplication.UnicodeUTF8))
        self.proxyLabel.setText(QtGui.QApplication.translate("SubAssetWindow", "Proxy List:", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.subAssetListWidget.isSortingEnabled()
        self.subAssetListWidget.setSortingEnabled(False)
        self.subAssetListWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.proxyListWidget.isSortingEnabled()
        self.proxyListWidget.setSortingEnabled(False)
        self.proxyListWidget.setSortingEnabled(__sortingEnabled)
        self.createSubAssetPushButton.setText(QtGui.QApplication.translate("SubAssetWindow", "Create SubAsset", None, QtGui.QApplication.UnicodeUTF8))
        self.createProxyPushButton.setText(QtGui.QApplication.translate("SubAssetWindow", "Create Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.removeSubAssetPushButton.setText(QtGui.QApplication.translate("SubAssetWindow", "Remove SubAsset", None, QtGui.QApplication.UnicodeUTF8))
        self.removeProxyPushButton.setText(QtGui.QApplication.translate("SubAssetWindow", "Remove Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.addSelSubAssetPushButton.setText(QtGui.QApplication.translate("SubAssetWindow", "Add Selection to SubAsset", None, QtGui.QApplication.UnicodeUTF8))
        self.addSelProxyPushButton.setText(QtGui.QApplication.translate("SubAssetWindow", "Add Selection to Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.removeSelSubAssetPushButton.setText(QtGui.QApplication.translate("SubAssetWindow", "Remove Selection from SubAsset", None, QtGui.QApplication.UnicodeUTF8))
        self.removeSelProxyPushButton.setText(QtGui.QApplication.translate("SubAssetWindow", "Remove Selection from Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("SubAssetWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("SubAssetWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("SubAssetWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))

        self.actionHelp_on_AssetDialog.setText(QtGui.QApplication.translate("SubAssetWindow", "Help on SubSetDialog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIsolateView.setText(QtGui.QApplication.translate("AssetWindow", "Isolate View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("AssetWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("AssetWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))